import * as FileSystem from 'expo-file-system/legacy';
import { api } from './api';
import { vault } from './vault';
import { fromB64, toB64 } from './crypto';

/**
 * Moving already-encrypted bytes to the server.
 *
 * A port of the web client's `lib/upload.js`, with one structural difference:
 * the browser hands a Blob to `FormData` and lets the platform stream it, while
 * React Native's `FormData` takes a **file URI** and streams from disk. So the
 * ciphertext is written to a scratch file first and uploaded from there, which
 * also keeps a 40 MB video out of the JS heap during the transfer.
 *
 * Small files go up in one request; anything larger is chunked, so a dropped
 * connection costs the chunks that were in flight rather than the whole upload.
 * Sessions are remembered against a fingerprint of the bytes, which is what
 * makes resume-after-relaunch work.
 */

const CHUNK_SIZE = 1024 * 1024;
const CONCURRENCY = 3;
const MAX_ATTEMPTS = 4;
const SINGLE_SHOT_LIMIT = 512 * 1024;
const SESSIONS_KEY = 'uploadSessions';
const SESSION_TTL_MS = 20 * 60 * 60 * 1000; // under the server's 24h sweep

const SCRATCH = FileSystem.cacheDirectory + 'outbound/';

/* ────────────────────────── scratch files ────────────────────────── */

async function writeScratch(base64, name) {
  try {
    await FileSystem.makeDirectoryAsync(SCRATCH, { intermediates: true });
  } catch {
    /* already there */
  }
  const path = SCRATCH + name;
  await FileSystem.writeAsStringAsync(path, base64, {
    encoding: FileSystem.EncodingType.Base64,
  });
  return path;
}

const removeScratch = (path) => FileSystem.deleteAsync(path, { idempotent: true }).catch(() => {});

/* ─────────────────────────── session bookkeeping ─────────────────────────── */

async function loadSessions() {
  const all = (await vault.getMeta(SESSIONS_KEY)) || {};
  const now = Date.now();
  // Prune as we read: a session the server has already swept is worse than no
  // session, because resuming it would 404 on every chunk.
  const live = Object.fromEntries(
    Object.entries(all).filter(([, s]) => now - (s.at || 0) < SESSION_TTL_MS)
  );
  if (Object.keys(live).length !== Object.keys(all).length) {
    await vault.setMeta(SESSIONS_KEY, live);
  }
  return live;
}

async function rememberSession(fingerprint, session) {
  const all = await loadSessions();
  all[fingerprint] = { ...session, at: Date.now() };
  await vault.setMeta(SESSIONS_KEY, all);
}

async function forgetSession(fingerprint) {
  const all = await loadSessions();
  delete all[fingerprint];
  await vault.setMeta(SESSIONS_KEY, all);
}

/* ───────────────────────────── retrying ───────────────────────────── */

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Retries what looks transient; gives up at once on a 4xx. */
async function withRetry(fn) {
  let lastError;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
    try {
      return await fn();
    } catch (err) {
      lastError = err;
      // A rejected chunk will be rejected again; only 5xx, timeouts and network
      // failures are worth another go.
      if (err.status && err.status >= 400 && err.status < 500) throw err;
      if (attempt === MAX_ATTEMPTS) break;
      await sleep(Math.min(2 ** attempt * 250, 4000));
    }
  }
  throw lastError;
}

/* ───────────────────────────── the upload ───────────────────────────── */

/**
 * Sends already-encrypted bytes and returns the stored file record.
 *
 * `ciphertext` is base64 because that is what both the cipher and the
 * filesystem speak; it is never decoded into a JS array for the single-shot
 * path, which is the common one.
 */
export async function send(ciphertext, { bucket = 'media', onProgress, filename = 'blob.bin' } = {}) {
  const byteLength = Math.floor((ciphertext.length * 3) / 4);

  if (byteLength <= SINGLE_SHOT_LIMIT) {
    return singleShot(ciphertext, { bucket, onProgress, filename });
  }
  return resumable(ciphertext, { bucket, onProgress });
}

async function singleShot(ciphertext, { bucket, onProgress, filename }) {
  const scratch = await writeScratch(ciphertext, 'up_' + Date.now() + '_' + Math.random().toString(36).slice(2, 8));

  try {
    const form = new FormData();
    form.append('files', {
      uri: scratch.startsWith('file://') ? scratch : 'file://' + scratch,
      name: filename,
      type: 'application/octet-stream',
    });

    /* Content-Type is deliberately not set.
     *
     * multipart/form-data is only parseable with the `boundary` parameter, and
     * that is generated by the networking layer when it serialises the body.
     * Setting the header by hand overwrites it *without* a boundary, so multer
     * sees a body it cannot split and reports no files at all — which is what
     * made every attachment fail with a message that pointed nowhere near the
     * cause. Leaving it unset lets the runtime fill in both. */
    const { data } = await withRetry(() =>
      api.post('/uploads/' + shortBucket(bucket), form, {
        timeout: 120_000,
        onUploadProgress: (e) => onProgress?.(e.total ? e.loaded / e.total : 0),
      })
    );

    onProgress?.(1);
    return data.files[0];
  } finally {
    removeScratch(scratch);
  }
}

async function resumable(ciphertext, { bucket, onProgress }) {
  const bytes = fromB64(ciphertext);

  // Cheap, stable fingerprint. A cryptographic digest would be better but
  // costs a full pass in JS over something we are about to upload anyway;
  // length plus a sampled checksum is enough to tell two files apart.
  const fingerprint = bucket + ':' + bytes.length + ':' + sampleChecksum(bytes);

  const session = await resumeOrBegin({ fingerprint, bytes, bucket });
  const { id, chunkSize, chunks } = session;

  const queue = Array.from({ length: chunks }, (_, i) => i).filter(
    (i) => !session.received.includes(i)
  );
  let done = chunks - queue.length;
  const report = () => onProgress?.(chunks ? done / chunks : 1);
  report();

  const worker = async () => {
    while (queue.length) {
      const index = queue.shift();
      const part = bytes.slice(index * chunkSize, Math.min((index + 1) * chunkSize, bytes.length));

      await withRetry(() =>
        api.put('/uploads/resumable/' + id + '/' + index, part, {
          headers: { 'Content-Type': 'application/octet-stream' },
          timeout: 60_000,
        })
      );

      done += 1;
      report();
    }
  };

  try {
    await Promise.all(
      Array.from({ length: Math.min(CONCURRENCY, queue.length || 1) }, worker)
    );

    const { data } = await withRetry(() => api.post('/uploads/resumable/' + id + '/complete'));
    await forgetSession(fingerprint);
    return data.file;
  } catch (err) {
    // The session is deliberately kept on failure — that is the whole point.
    throw err;
  }
}

/** Picks up a stored session if the server still has it, else starts fresh. */
async function resumeOrBegin({ fingerprint, bytes, bucket }) {
  const remembered = (await loadSessions())[fingerprint];

  if (remembered?.id) {
    try {
      const { data } = await api.get('/uploads/resumable/' + remembered.id);
      if (!data.upload.complete) {
        return {
          id: data.upload.id,
          chunkSize: data.upload.chunkSize,
          chunks: data.upload.chunks,
          received: data.upload.received,
        };
      }
    } catch {
      await forgetSession(fingerprint);
    }
  }

  const { data } = await api.post('/uploads/resumable', {
    size: bytes.length,
    chunkSize: CHUNK_SIZE,
    bucket,
    checksum: sampleChecksum(bytes),
  });

  const session = {
    id: data.upload.id,
    chunkSize: data.upload.chunkSize,
    chunks: data.upload.chunks,
    received: data.upload.received || [],
  };
  await rememberSession(fingerprint, session);
  return session;
}

/** Samples rather than hashes — see the note at the call site. */
function sampleChecksum(bytes) {
  let hash = 0;
  const step = Math.max(1, Math.floor(bytes.length / 4096));
  for (let i = 0; i < bytes.length; i += step) {
    hash = (hash * 31 + bytes[i]) | 0;
  }
  return Math.abs(hash).toString(36) + '-' + bytes.length.toString(36);
}

// The single-shot routes are named for what they carry, not for their bucket.
const shortBucket = (bucket) => (bucket === 'stories' ? 'story-media' : bucket);

export { toB64, fromB64 };
